# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: ACCELQ Github-A Connect
  # You may pin to the exact commit or the version.
  # uses: ravin-accelq/accelq-ci-github-actions@2686194162077054ea3d1f227dc8fb8b0d2eb3d5
  uses: ravin-accelq/accelq-ci-github-actions@v1.4
  with:
    # Your ACCELQ Application URL in the exact following format: https://<hostname>:<port_num>
    appURL: https://app.accelq.io
    # Your ACCELQ User ID
    userName: phani.yvn@aqsupport.com
    # API key available in Profile section of ACCELQ
    apiKey: 7wkGaMKar3UOx_ut-n6LedUC9xH6FXHDJr87hPb8JXw
    # Tenant Code displayed in the Profile section of ACCELQ
    tenantCode: aqsupport
    # This ID should come from the CI job you saved in ACCELQ application
    jobId: 2703
    # Run Params(optional) should be JSON string form example: '{"username": "John Todd", "password": "bxW&=UVw"}'
    runParam: # optional
    # Proxy Host (optional)
    proxyHost: # optional
    # Proxy Port (optional)
    proxyPort: # optional
    # Percentage ACCELQ test case failure (Optional), beyond which this Step in the Pipeline will be marked as a failure. If this is zero, even a single failed test will cause the Step to fail. If you never want to fail the Pipeline Step due to failing Automation tests, input -1. Input a valid integer between 0 and 100 or, -1.
    stepFailureThreshold: # optional
    # Maximum time to wait for the job to be picked up by an ACCELQ Agent. Default is 15 mins.
    maxWaitTimeInMins: # optional
          
